development:
  adapter: mysql2
  encoding: utf8
  database: rail_dev
  username: root
  host: localhost
test:
  adapter: mysql2
  encoding: utf8
  database: rail_test
  username: root
  host: localhost
production:
  adapter: mysql2
  encoding: utf8
  database: rail_prd
  username: root
  host: localhost
